# Generated by Django 3.2.3 on 2021-06-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210616_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='price',
            field=models.IntegerField(default=models.IntegerField(), null=True),
        ),
    ]
