# Generated by Django 3.2.3 on 2021-06-16 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlistings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
