# Generated by Django 3.2.3 on 2021-06-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210616_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='open',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
