# Generated by Django 3.2.3 on 2021-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comments_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='open',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
    ]
